import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal, boolean } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), passwordHash: text("passwordHash"), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const customerProfiles = mysqlTable("customer_profiles", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), kind: mysqlEnum("kind", ["individual", "company"]).default("individual").notNull(), phone: varchar("phone", { length: 32 }), city: varchar("city", { length: 120 }).notNull(), state: varchar("state", { length: 2 }).default("RJ").notNull(), address: text("address"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const professionalProfiles = mysqlTable("professional_profiles", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), businessName: varchar("businessName", { length: 160 }), phone: varchar("phone", { length: 32 }), bio: text("bio"), cities: text("cities").notNull(), specialties: text("specialties").notNull(), equipmentTypes: text("equipmentTypes"), serviceTypes: text("serviceTypes"), certifications: text("certifications"), experienceYears: int("experienceYears").default(0).notNull(), availability: varchar("availability", { length: 120 }).default("flexível").notNull(), rating: decimal("rating", { precision: 3, scale: 2 }).default("0"), reviewCount: int("reviewCount").default(0).notNull(), verified: boolean("verified").default(false).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const serviceCategories = mysqlTable("service_categories", { id: int("id").autoincrement().primaryKey(), slug: varchar("slug", { length: 80 }).notNull().unique(), name: varchar("name", { length: 120 }).notNull(), services: text("services").notNull(), equipment: text("equipment").notNull(), active: boolean("active").default(true).notNull() });
export const serviceRequests = mysqlTable("service_requests", { id: int("id").autoincrement().primaryKey(), customerId: int("customerId").notNull(), category: varchar("category", { length: 80 }).notNull(), serviceType: varchar("serviceType", { length: 120 }).notNull(), equipment: varchar("equipment", { length: 160 }).notNull(), brand: varchar("brand", { length: 120 }), model: varchar("model", { length: 120 }), description: text("description").notNull(), photos: text("photos"), city: varchar("city", { length: 120 }).notNull(), state: varchar("state", { length: 2 }).default("RJ").notNull(), address: text("address"), urgency: mysqlEnum("urgency", ["normal", "urgente", "emergencial"]).default("normal").notNull(), availability: varchar("availability", { length: 120 }).notNull(), status: mysqlEnum("status", ["open", "matched", "interested", "hired", "in_progress", "completed", "canceled"]).default("open").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const matches = mysqlTable("matches", { id: int("id").autoincrement().primaryKey(), requestId: int("requestId").notNull(), professionalId: int("professionalId").notNull(), score: int("score").default(0).notNull(), reason: text("reason"), status: mysqlEnum("status", ["notified", "interested", "declined", "expired"]).default("notified").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const proposals = mysqlTable("proposals", { id: int("id").autoincrement().primaryKey(), requestId: int("requestId").notNull(), professionalId: int("professionalId").notNull(), amount: decimal("amount", { precision: 10, scale: 2 }).notNull(), deadline: varchar("deadline", { length: 120 }).notNull(), description: text("description").notNull(), notes: text("notes"), status: mysqlEnum("status", ["sent", "accepted", "rejected"]).default("sent").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const services = mysqlTable("services", { id: int("id").autoincrement().primaryKey(), requestId: int("requestId").notNull(), proposalId: int("proposalId").notNull(), customerId: int("customerId").notNull(), professionalId: int("professionalId").notNull(), status: mysqlEnum("status", ["hired", "in_progress", "completed", "canceled"]).default("hired").notNull(), startedAt: timestamp("startedAt"), completedAt: timestamp("completedAt"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const reviews = mysqlTable("reviews", { id: int("id").autoincrement().primaryKey(), serviceId: int("serviceId").notNull(), customerId: int("customerId").notNull(), professionalId: int("professionalId").notNull(), overall: int("overall").notNull(), quality: int("quality").notNull(), punctuality: int("punctuality").notNull(), service: int("service").notNull(), comment: text("comment"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const notifications = mysqlTable("notifications", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), title: varchar("title", { length: 160 }).notNull(), message: text("message").notNull(), read: boolean("read").default(false).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type ServiceRequest = typeof serviceRequests.$inferSelect; export type ProfessionalProfile = typeof professionalProfiles.$inferSelect; export type Proposal = typeof proposals.$inferSelect; export type Service = typeof services.$inferSelect;
