import { and, desc, eq, sql, count, or } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, users, customerProfiles, professionalProfiles, serviceRequests, matches, proposals, services, reviews, notifications } from "../drizzle/schema";
import { ENV } from './_core/env';
let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (e) { console.warn('[Database] Failed to connect', e); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error('User openId is required'); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId, name: user.name, email: user.email, passwordHash: user.passwordHash, loginMethod: user.loginMethod, role: user.role ?? 'user', lastSignedIn: user.lastSignedIn ?? new Date() }; await db.insert(users).values(values).onDuplicateKeyUpdate({ set: { name: values.name, email: values.email, loginMethod: values.loginMethod, lastSignedIn: values.lastSignedIn, role: values.role } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function getUserById(id: number) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(users).where(eq(users.id, id)).limit(1))[0]; }
export async function getUserByEmail(email: string) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(users).where(eq(users.email, email)).limit(1))[0]; }
export async function getCustomerRequests(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(serviceRequests).where(eq(serviceRequests.customerId, userId)).orderBy(desc(serviceRequests.createdAt)); }
export async function getOpenRequests() { const db = await getDb(); if (!db) return []; return db.select().from(serviceRequests).where(or(eq(serviceRequests.status, 'open'), eq(serviceRequests.status, 'matched'), eq(serviceRequests.status, 'interested'))).orderBy(desc(serviceRequests.createdAt)); }
export async function getProfessionalProfile(userId: number) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(professionalProfiles).where(eq(professionalProfiles.userId, userId)).limit(1))[0]; }
export async function getCustomerProfile(userId: number) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(customerProfiles).where(eq(customerProfiles.userId, userId)).limit(1))[0]; }
export async function getMetrics() { const db = await getDb(); if (!db) return { customers: 0, professionals: 0, requests: 0, matches: 0, interests: 0, proposals: 0, hires: 0, completed: 0, reviews: 0 }; const tables = [customerProfiles, professionalProfiles, serviceRequests, matches, proposals, services, reviews]; const values = await Promise.all(tables.map(t => db.select({ value: count() }).from(t))); const interests = await db.select({ value: count() }).from(matches).where(eq(matches.status, 'interested')); const completed = await db.select({ value: count() }).from(services).where(eq(services.status, 'completed')); return { customers: values[0][0]?.value ?? 0, professionals: values[1][0]?.value ?? 0, requests: values[2][0]?.value ?? 0, matches: values[3][0]?.value ?? 0, interests: interests[0]?.value ?? 0, proposals: values[4][0]?.value ?? 0, hires: values[5][0]?.value ?? 0, completed: completed[0]?.value ?? 0, reviews: values[6][0]?.value ?? 0 }; }
export { users, customerProfiles, professionalProfiles, serviceRequests, matches, proposals, services, reviews, notifications };
