import type { Express, Request, Response } from 'express';
import { serialize } from 'cookie';
import crypto from 'node:crypto';
import { SignJWT } from 'jose';
import { getDb, getUserByEmail } from './db';
import { users } from '../drizzle/schema';
import { ENV } from './_core/env';
import { COOKIE_NAME } from '../shared/const';

function hash(password: string, salt: string) { return crypto.scryptSync(password, salt, 64).toString('hex'); }
function makeHash(password: string) { const salt = crypto.randomBytes(16).toString('hex'); return `${salt}:${hash(password, salt)}`; }
function verify(password: string, stored: string) { const [salt, expected] = stored.split(':'); return Boolean(salt && expected) && crypto.timingSafeEqual(Buffer.from(hash(password, salt), 'hex'), Buffer.from(expected, 'hex')); }
async function session(userId: number) { return new SignJWT({ role: 'user' }).setProtectedHeader({ alg: 'HS256' }).setSubject(String(userId)).setIssuedAt().setExpirationTime('30d').sign(new TextEncoder().encode(ENV.jwtSecret)); }
function page(error = '', redirect = '/') { return `<!doctype html><meta charset="utf-8"><title>Entrar — ClimaMatch</title><style>body{font-family:system-ui;max-width:420px;margin:10vh auto;padding:24px;background:#f7f4ee;color:#0b332d}form{display:grid;gap:12px;background:#fffdf8;padding:24px;border-radius:18px}input,button{padding:12px;border-radius:10px;border:1px solid #ccd9cf;font-size:16px}button{background:#0c6b58;color:white;border:0;cursor:pointer}.error{color:#a43d32}</style><h1>Entrar no ClimaMatch</h1>${error ? `<p class="error">${error}</p>` : ''}<form method="post" action="/api/auth/login"><input type="hidden" name="redirect" value="${redirect.replace(/"/g, '&quot;')}"><label>Nome (no primeiro acesso)<input name="name" required></label><label>E-mail<input type="email" name="email" required></label><label>Senha<input type="password" name="password" minlength="8" required></label><button>Entrar ou criar conta</button></form>`; }
export function registerLocalAuth(app: Express) { app.get('/api/auth/login', (req, res) => res.type('html').send(page('', String(req.query.redirect || '/')))); app.post('/api/auth/login', async (req: Request, res: Response) => { const email = String(req.body.email || '').trim().toLowerCase(); const name = String(req.body.name || '').trim(); const password = String(req.body.password || ''); const redirect = String(req.body.redirect || '/'); if (!email || !name || password.length < 8) return res.status(400).type('html').send(page('Informe nome, e-mail e uma senha de pelo menos 8 caracteres.', redirect)); const db = await getDb(); if (!db) return res.status(503).type('html').send(page('Banco de dados indisponível.', redirect)); let user = await getUserByEmail(email); if (!user) { const inserted = await db.insert(users).values({ openId: `local:${crypto.randomUUID()}`, name, email, passwordHash: makeHash(password), loginMethod: 'local' }); user = (await getUserByEmail(email))!; if (!user) return res.status(500).send('Falha ao criar usuário'); } else if (!user.passwordHash || !verify(password, user.passwordHash)) return res.status(401).type('html').send(page('E-mail ou senha inválidos.', redirect)); const token = await session(user.id); res.setHeader('Set-Cookie', serialize(COOKIE_NAME, token, { httpOnly: true, sameSite: 'lax', secure: ENV.isProduction, path: '/', maxAge: 60 * 60 * 24 * 30 })); res.redirect(redirect); }); }
