import { z } from 'zod';
import { COOKIE_NAME } from '@shared/const';
import { getSessionCookieOptions } from './_core/cookies';
import { systemRouter } from './_core/systemRouter';
import { publicProcedure, protectedProcedure, router } from './_core/trpc';
import { getDb, upsertUser, getCustomerRequests, getOpenRequests, getProfessionalProfile, getCustomerProfile, getMetrics, customerProfiles, professionalProfiles, serviceRequests, matches, proposals, services, reviews, notifications } from './db';
import { eq, and, desc, sql } from 'drizzle-orm';
import { scoreProfessional } from './matching';
import { translateProblem } from './problem-mapping';
import { storagePut } from './storage';
import { sanitizeUploadName, validateMedia } from './media';
import { buildWhatsAppMessage, sendWhatsAppNotification } from './whatsapp';

const categories = [
  { slug: 'climatizacao', name: 'Climatização', services: ['Instalação','Manutenção preventiva','Manutenção corretiva','Higienização','Diagnóstico','PMOC','Retirada','Reinstalação','Troca de equipamento'], equipment: ['Split','Multi Split','Cassete','Piso-teto','VRF/VRV','Rooftop','Central'] },
  { slug: 'comercial', name: 'Refrigeração comercial', services: ['Manutenção corretiva','Diagnóstico','Instalação','Higienização'], equipment: ['Balcão refrigerado','Expositor','Freezer','Ilha','Geladeira comercial','Máquina de gelo','Câmara fria'] },
  { slug: 'industrial', name: 'Refrigeração industrial', services: ['Manutenção corretiva','Diagnóstico','Instalação','PMOC'], equipment: ['Câmara fria','Chiller','Sistemas industriais','Compressores','Condensação'] },
  { slug: 'residencial', name: 'Refrigeração residencial', services: ['Manutenção corretiva','Diagnóstico','Instalação'], equipment: ['Geladeira','Freezer','Outros'] },
];
const cities = ['Cabo Frio','Araruama','São Pedro da Aldeia','Arraial do Cabo','Búzios','Saquarema'];
const requireRole = (role: 'customer'|'professional'|'admin') => protectedProcedure.use(({ ctx, next }) => { if (role === 'admin' && ctx.user.role !== 'admin') throw new Error('Acesso restrito ao administrador'); return next({ ctx }); });

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(({ ctx }) => ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const opts = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...opts, maxAge: -1 }); return { success: true } as const; }) }),
  catalog: router({ categories: publicProcedure.query(() => categories), cities: publicProcedure.query(() => cities) }),
  profile: router({
    me: protectedProcedure.query(async ({ ctx }) => ({ customer: await getCustomerProfile(ctx.user.id), professional: await getProfessionalProfile(ctx.user.id) })),
    saveCustomer: protectedProcedure.input(z.object({ kind: z.enum(['individual','company']), phone: z.string().optional(), city: z.string(), state: z.string().length(2).default('RJ'), address: z.string().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { ok: true }; const existing = await getCustomerProfile(ctx.user.id); if (existing) await db.update(customerProfiles).set(input).where(eq(customerProfiles.userId, ctx.user.id)); else await db.insert(customerProfiles).values({ ...input, userId: ctx.user.id }); return { ok: true }; }),
    saveProfessional: protectedProcedure.input(z.object({ businessName: z.string().optional(), phone: z.string().optional(), bio: z.string().optional(), cities: z.array(z.string()).min(1), specialties: z.array(z.string()).min(1), equipmentTypes: z.array(z.string()).optional(), serviceTypes: z.array(z.string()).optional(), certifications: z.array(z.string()).optional(), experienceYears: z.number().int().min(0).default(0), availability: z.string().default('flexível') })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { ok: true }; const values = { ...input, userId: ctx.user.id, cities: input.cities.join(','), specialties: input.specialties.join(','), equipmentTypes: (input.equipmentTypes ?? []).join(','), serviceTypes: (input.serviceTypes ?? []).join(','), certifications: (input.certifications ?? []).join(',') }; const existing = await getProfessionalProfile(ctx.user.id); if (existing) await db.update(professionalProfiles).set(values).where(eq(professionalProfiles.userId, ctx.user.id)); else await db.insert(professionalProfiles).values(values); return { ok: true }; }),
  }),
  requests: router({
    mine: protectedProcedure.query(({ ctx }) => getCustomerRequests(ctx.user.id)),
    create: protectedProcedure.input(z.object({ problem: z.enum(['ar_nao_gela','ar_nao_liga','ar_pingando','ar_barulho','instalar_ar','limpar_ar','geladeira_freezer','outro','ajuda']), details: z.string().optional(), environment: z.enum(['Casa','Apartamento','Loja','Empresa']), city: z.string(), state: z.string().length(2).default('RJ'), address: z.string().optional(), urgency: z.enum(['normal','urgente','emergencial']), availability: z.string() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { id: 0, matched: 0 }; const translated = translateProblem(input.problem, input.details, input.environment); const request = { ...translated, city: input.city, availability: input.availability }; const inserted = await db.insert(serviceRequests).values({ category: translated.category, serviceType: translated.serviceType, equipment: translated.equipment, description: translated.description, customerId: ctx.user.id, city: input.city, state: input.state, address: input.address, urgency: input.urgency, availability: input.availability }); const requestId = Number(inserted[0].insertId); const pros = await db.select().from(professionalProfiles); let matched = 0; for (const pro of pros) { const result = scoreProfessional(request, pro); if (result.eligible) { await db.insert(matches).values({ requestId, professionalId: pro.id, score: result.score, reason: result.reason }); const message = `${translated.label} em ${input.city}. Veja os detalhes e diga se tem interesse.`; await db.insert(notifications).values({ userId: pro.userId, title: 'Nova oportunidade compatível', message }); void sendWhatsAppNotification(pro.phone, buildWhatsAppMessage(translated.label, input.city)).catch(error => console.warn('[WhatsApp] Notification failed:', error)); matched++; } } if (matched) await db.update(serviceRequests).set({ status: 'matched' }).where(eq(serviceRequests.id, requestId)); return { id: requestId, matched }; }),
    uploadMedia: protectedProcedure.input(z.object({ requestId: z.number().int().positive(), fileName: z.string().min(1).max(180), mimeType: z.enum(['image/jpeg','image/png','image/webp','video/mp4','video/quicktime']), dataBase64: z.string().min(1).max(16_000_000) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error('Banco de dados indisponível'); const request = (await db.select().from(serviceRequests).where(and(eq(serviceRequests.id, input.requestId), eq(serviceRequests.customerId, ctx.user.id))).limit(1))[0]; if (!request) throw new Error('Solicitação não encontrada'); const raw = input.dataBase64.replace(/^data:[^;]+;base64,/, ''); const bytes = Buffer.from(raw, 'base64'); validateMedia(input.mimeType, bytes.length); const stored = await storagePut(`requests/${ctx.user.id}/${input.requestId}/${sanitizeUploadName(input.fileName)}`, bytes, input.mimeType); const photos = request.photos ? `${request.photos},${stored.url}` : stored.url; await db.update(serviceRequests).set({ photos }).where(eq(serviceRequests.id, request.id)); return { url: stored.url }; }),
  }),
  professional: router({
    opportunities: protectedProcedure.query(async ({ ctx }) => { const profile = await getProfessionalProfile(ctx.user.id); const db = await getDb(); if (!db) return []; const rows = await getOpenRequests(); if (!profile) return rows; return rows.filter(r => profile.cities.toLowerCase().includes(r.city.toLowerCase()) || profile.specialties.toLowerCase().includes(r.category.toLowerCase())); }),
    notifications: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(notifications).where(eq(notifications.userId, ctx.user.id)).orderBy(desc(notifications.createdAt)).limit(20); }),
    markNotificationRead: protectedProcedure.input(z.object({ notificationId: z.number() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { ok: true }; await db.update(notifications).set({ read: true }).where(and(eq(notifications.id, input.notificationId), eq(notifications.userId, ctx.user.id))); return { ok: true }; }),
    interest: protectedProcedure.input(z.object({ requestId: z.number(), interested: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { ok: true }; const profile = await getProfessionalProfile(ctx.user.id); if (!profile) throw new Error('Crie seu perfil profissional antes de demonstrar interesse'); await db.insert(matches).values({ requestId: input.requestId, professionalId: profile.id, score: 80, reason: 'Interesse demonstrado pelo profissional', status: input.interested ? 'interested' : 'declined' }); if (input.interested) await db.update(serviceRequests).set({ status: 'interested' }).where(eq(serviceRequests.id, input.requestId)); return { ok: true }; }),
    proposals: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); const profile = await getProfessionalProfile(ctx.user.id); if (!db || !profile) return []; return db.select().from(proposals).where(eq(proposals.professionalId, profile.id)).orderBy(desc(proposals.createdAt)); }),
    sendProposal: protectedProcedure.input(z.object({ requestId: z.number(), amount: z.number().positive(), deadline: z.string(), description: z.string().min(10), notes: z.string().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); const profile = await getProfessionalProfile(ctx.user.id); if (!db || !profile) throw new Error('Perfil profissional não encontrado'); await db.insert(proposals).values({ ...input, amount: input.amount.toFixed(2), professionalId: profile.id }); return { ok: true }; }),
    services: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); const profile = await getProfessionalProfile(ctx.user.id); if (!db || !profile) return []; return db.select().from(services).where(eq(services.professionalId, profile.id)).orderBy(desc(services.createdAt)); }),
    updateService: protectedProcedure.input(z.object({ serviceId: z.number(), status: z.enum(['in_progress','completed','canceled']) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { ok: true }; const profile = await getProfessionalProfile(ctx.user.id); if (!profile) throw new Error('Perfil profissional não encontrado'); const current = (await db.select().from(services).where(and(eq(services.id, input.serviceId), eq(services.professionalId, profile.id))).limit(1))[0]; if (!current) throw new Error('Serviço não encontrado'); await db.update(services).set({ status: input.status, ...(input.status === 'in_progress' ? { startedAt: new Date() } : {}), ...(input.status === 'completed' ? { completedAt: new Date() } : {}) }).where(eq(services.id, input.serviceId)); await db.update(serviceRequests).set({ status: input.status === 'in_progress' ? 'in_progress' : input.status === 'completed' ? 'completed' : 'canceled' }).where(eq(serviceRequests.id, current.requestId)); return { ok: true }; }),
  }),
  proposals: router({ forRequest: protectedProcedure.input(z.object({ requestId: z.number() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) return []; const request = (await db.select().from(serviceRequests).where(and(eq(serviceRequests.id, input.requestId), eq(serviceRequests.customerId, ctx.user.id))).limit(1))[0]; if (!request) throw new Error('Solicitação não encontrada'); return db.select().from(proposals).where(eq(proposals.requestId, input.requestId)).orderBy(desc(proposals.createdAt)); }), choose: protectedProcedure.input(z.object({ proposalId: z.number() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { ok: true }; const proposal = (await db.select().from(proposals).where(eq(proposals.id, input.proposalId)).limit(1))[0]; if (!proposal) throw new Error('Proposta não encontrada'); const request = (await db.select().from(serviceRequests).where(and(eq(serviceRequests.id, proposal.requestId), eq(serviceRequests.customerId, ctx.user.id))).limit(1))[0]; if (!request) throw new Error('Solicitação não encontrada'); await db.update(proposals).set({ status: 'accepted' }).where(eq(proposals.id, proposal.id)); await db.update(serviceRequests).set({ status: 'hired' }).where(eq(serviceRequests.id, request.id)); await db.insert(services).values({ requestId: request.id, proposalId: proposal.id, customerId: ctx.user.id, professionalId: proposal.professionalId }); return { ok: true }; }) }),
  service: router({ mine: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select().from(services).where(eq(services.customerId, ctx.user.id)).orderBy(desc(services.createdAt)); }), review: protectedProcedure.input(z.object({ serviceId: z.number(), overall: z.number().min(1).max(5), quality: z.number().min(1).max(5), punctuality: z.number().min(1).max(5), service: z.number().min(1).max(5), comment: z.string().max(1200).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { ok: true }; const svc = (await db.select().from(services).where(and(eq(services.id, input.serviceId), eq(services.customerId, ctx.user.id))).limit(1))[0]; if (!svc || svc.status !== 'completed') throw new Error('Avaliação disponível somente após a conclusão'); const existing = (await db.select().from(reviews).where(eq(reviews.serviceId, input.serviceId)).limit(1))[0]; if (existing) throw new Error('Este serviço já foi avaliado'); await db.insert(reviews).values({ ...input, customerId: ctx.user.id, professionalId: svc.professionalId }); await db.update(professionalProfiles).set({ reviewCount: sql`${professionalProfiles.reviewCount} + 1` }).where(eq(professionalProfiles.id, svc.professionalId)); return { ok: true }; }) }),
  admin: router({ metrics: protectedProcedure.query(({ ctx }) => { if (ctx.user.role !== 'admin') throw new Error('Acesso restrito'); return getMetrics(); }), recent: protectedProcedure.query(async ({ ctx }) => { if (ctx.user.role !== 'admin') throw new Error('Acesso restrito'); const db = await getDb(); if (!db) return []; return db.select().from(serviceRequests).orderBy(desc(serviceRequests.createdAt)).limit(20); }) }),
});
export type AppRouter = typeof appRouter;
